# Generated by Django 5.2 on 2025-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_reporter_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='descrição',
            field=models.CharField(default='', help_text='Insira a descrição do escritor', max_length=200),
        ),
    ]
