# Generated by Django 5.2 on 2025-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0004_reporter_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='idade',
            field=models.CharField(default=0, help_text='Digite sua idade:', max_length=3, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='reporter',
            name='nacionalidade',
            field=models.CharField(default='Não especificado', help_text='Insira aqui sua nacionalidade', max_length=100, verbose_name='Nacionalidade'),
        ),
    ]
