# Generated by Django 5.2 on 2025-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0005_reporter_idade_reporter_nacionalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(default='Não encontrada', help_text='Insira a idade', verbose_name='Idade'),
        ),
    ]
