# Generated by Django 5.2 on 2025-04-28 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0005_reporter_idade_reporter_nacionalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Não especificado', help_text='Insira o nome da revista', max_length=100, verbose_name='Nome da revista')),
                ('edition', models.IntegerField(help_text='Insira a edição da Revista', verbose_name='Edição da Revista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(help_text='Selecione o repórter', on_delete=django.db.models.deletion.CASCADE, to='meuapp.reporter', verbose_name='Reporter'),
        ),
        migrations.AddField(
            model_name='article',
            name='magazine',
            field=models.ManyToManyField(help_text='Selecione as revistas', to='meuapp.magazine', verbose_name='Revistas'),
        ),
    ]
