# Generated by Django 5.2 on 2025-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0007_alter_account_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(help_text='Insira a idade', verbose_name='Idade'),
        ),
    ]
