# Generated by Django 5.2 on 2025-04-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0006_magazine_alter_article_reporter_article_magazine'),
        ('meuapp', '0009_alter_account_age'),
    ]

    operations = [
    ]
